M48
; DRILL file {KiCad (6.0.11)} date Sun Feb  5 16:44:36 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-05T16:44:36-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1200
%
G90
G05
T1
X7.3632Y-4.8955
X7.3632Y-5.2955
T2
X6.0236Y-2.9331
X6.9921Y-3.2756
T0
M30
